---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        defaultSettings:
          backupTarget: cifs://192.168.10.251/Backups
          backupTargetCredentialSecret: cifs-credentials
        ingress:
          enabled: true
          ingressClassName: traefik
          host: longhorn.vfd.lan