---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        service:
          annotations:
            external-dns.alpha.kubernetes.io/hostname: traefik.vfd.lan
