---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        service:
          annotations:
            external-dns.alpha.kubernetes.io/hostname: ingress.vfd.lan
        ingressRoute:
          dashboard:
            enabled: true
            matchRule: Host(`traefik.vfd.lan`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
            annotations:
              external-dns.alpha.kubernetes.io/target: ingress.vfd.lan
            entryPoints: ["websecure"]
          healthcheck:
            enabled: true
            matchRule: Host(`traefik.vfd.lan`) && PathPrefix(`/ping`)
            annotations:
              external-dns.alpha.kubernetes.io/target: ingress.vfd.lan
            entryPoints: ["websecure"]